### PR TITLE
Added flag for verbose mode and custom file extensions

### PR DESCRIPTION
**Pull request by zareone**
Hi there!

I had the need to have Gin to trigger rebuild based on files other than .go (.ace templates for example), so I added this feature, hoping it'll be useful for others. OK, actually a reload of the server would suffice (Ace caches parsed templates), but this is handy anyway... 

This is my first PR (to any public project), but be merciless!

### CODE REVIEW

**Comment by timsayshey** [comment]
@codegangsta Lovin' Gin, thank you! We need this feature, any chance we can get it merged?

**Comment by spence** [comment]
Bump on this? Would be nice to see which file was changed.

**Comment by ibash** [comment]
@spence want to create a new PR with these changes and conflicts resolved?

**Comment by zareone** [comment]
@ibash I'm not using gin anymore (moved to [reflex](https://github.com/cespare/reflex)), but I can rebase the PR.

**Comment by ibash** [comment]
@zareone would be appreciated!

**Comment by zareone** [comment]
@ibash OK, I've been having a look at my PR (had forgot about it, since it's been a long time), but I don't think it makes much sense to merge it anymore. 

I see at some point, the option to watch for all files (not just .go files) was added. So the --exts flag would be redundant now.

As for the verbose flag, it doesn't add any info on which specific files have been changed, so it won't serve @spence 's purposes.

**Comment by ibash** [comment]
@zareone thanks for taking a look - going to close this out then. @spence if this is still useful to you feel free to make a new PR.

**Pull request closed without merging**
