### PR TITLE
Added push notifications when a build fails or finished

### PR DESCRIPTION
**Pull request by benbotwin**
It's a lot nicer getting immediate feedback via a push notification when a build finishes. This way you never really need to look at the terminal other than for logs.

### CODE REVIEW

**Comment by benbotwin** [comment]
Any idea why that build is failing? I trying `go get`ting on a clean `GOPATH` and it ran fine.

**Comment by ibash** [comment]
@benbotwin looks like it might be due to wercker using an old version of go:
```
$ go version
go version go1.2 linux/amd64
$ go get -t ./...
# github.com/mattn/go-shellwords
../../mattn/go-shellwords/util_posix.go:17: eerr.Stderr undefined (type *exec.ExitError has no field or method Stderr)
```

You could try adding a wercker.yml with a newer version

**Comment by benbotwin** [comment]
apparently wrecker doesn't have any other versions.

Also, i'll clean up these commits and make a new PR once I have this figured out

**Comment by ibash** [comment]
@benbotwin does `box: golang:1.9.1` work?

**Comment by benbotwin** [comment]
nope, is there a list of wrecker boxes somewhere?

**Comment by benbotwin** [comment]
Nope. @ibash is there a list of wrecker boxes somewhere? I thought it was pulling containers from docker hub, but that doesn't seem to be the case.

**Comment by benbotwin** [comment]
@ibash I got the build working and I squashed all the commits here 😄 . Let me know if there's anything you think would need adding or fixing

**Comment by ibash** [comment]
Thanks @benbotwin! There seems to be one test that is not passing, barring that this is good to go!

**Comment by benbotwin** [comment]
All the tests run fine on my machine:tm: 

But I don't see which test is failing.

**Comment by benbotwin** [comment]
@ibash I'm not sure what that failed but it looks all good now :)

**Comment by ibash** [comment]
Thank you!!

**Pull request merged**
